version: "3.8"
services:
  merlin-tensorflow:
    image: nvcr.io/nvidia/merlin/merlin-tensorflow:23.12
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    ports:
      - "8888:8888" # Jupyter Lab
      - "8797:8787" # Dask Scheduler
      - "8796:8786" # Dask Workers
    ipc: host
    cap_add:
      - SYS_NICE
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./data:/workspace/data
      - ./src:/try-merlin/src
    command: >
      bash -c "cd / && jupyter-lab --allow-root --ip='0.0.0.0' --NotebookApp.token='' --NotebookApp.password=''"
