version: "3.8"
services:
  merlin-tensorflow-cpu:
    image: nvcr.io/nvidia/merlin/merlin-tensorflow:23.12
    ports:
      - "8888:8888" # Jupyter Lab
      - "8797:8787" # Dask Scheduler
      - "8796:8786" # Dask Workers
    ipc: host
    cap_add:
      - SYS_NICE
    environment:
      - NVIDIA_VISIBLE_DEVICES=""
      - NVIDIA_DRIVER_CAPABILITIES=""
      - NUMBA_DISABLE_JIT="1"
    volumes:
      - ./data:/try-merlin/data
      - ./explore:/try-merlin/explore
    command: >
      bash -c "
      pip install --upgrade pip && 
      pip install feast faiss-cpu &&
      pip install 'dask[dataframe]' --upgrade &&
      pip install -U pandas &&
      pip install -U numba &&
      pip install pyarrow fastparquet seedir &&
      cd / && 
      jupyter-lab --allow-root --ip='0.0.0.0' --NotebookApp.token=''
      "
