version: "3.8"
services:
  merlin-tensorflow-gpu:
    image: nvcr.io/nvidia/merlin/merlin-tensorflow:23.12 # GPU image remains the same
    runtime: nvidia # Enables GPU runtime
    ports:
      - "8888:8888" # Jupyter Lab
      - "8797:8787" # Dask Scheduler
      - "8796:8786" # Dask Workers
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]

    cap_add:
      - SYS_NICE
    environment:
      - NVIDIA_VISIBLE_DEVICES=all # Ensures that all GPUs are available
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility # Required GPU capabilities
    volumes:
      - ./data:/try-merlin/data
      - ./src:/try-merlin/src
    command: >
      bash -c "
      pip install --upgrade pip && 
      pip install pyarrow fastparquet feast faiss-gpu seedir && 
      cd / &&
      jupyter-lab --allow-root --ip='0.0.0.0' --NotebookApp.token=''
      "
